version: '3'
  
services:
  db:
    networks:
      - db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hh-location
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - "./database:/var/lib/mysql"
  app:
    networks:
      - db
    image: registry.handh.ru:5000/location-app:latest
    volumes:
      - "./config:/go/bin/config"
    environment:
      MYSQL_HOST: "db:3306"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "hh-location"      

networks:
  db:
    external: false
